import {
  IconPhoto,
  IconVideo,
  IconVolume,
  IconFile,
  IconLink,
  IconBrandDiscord,
  IconCamera,
  IconNote,
  IconPencil,
  IconFlag,
  IconFlagOff,
  IconRefresh,
  IconDownload,
  IconX,
  IconChevronLeft,
  IconChevronRight,
  IconPlus,
  IconCheck,
  IconAlertTriangle,
  IconQuestionMark,
  IconEye,
  IconHistory,
  IconSettings,
  IconTrash,
  IconSearch,
  IconKeyboard,
  IconLayoutDashboard,
  IconGavel,
  IconFolder,
  IconClipboardList,
  IconShieldCheck,
  IconFilter,
  IconMessageReport,
  IconMenu2,
  IconClipboard,
  IconSend,
  IconTag,
  IconFileExport,
  IconBrush,
  IconPlayerPlay,
  IconPlayerPause,
  IconLayoutGrid,
  IconList,
  IconArrowsExchange,
  IconChartBar,
  IconUser,
  IconCalendar,
  IconUserPlus,
  IconUserMinus,
  IconShare,
  IconColumns,
  IconLayoutRows,
  IconLock,
  IconUsers,
  IconTrophy,
  IconMicrophone,
  IconBan,
  IconMessage,
  IconStarFilled,
  IconLogout,
  type Icon,
} from '@tabler/icons-react';
import type { EvidenceType } from '@/lib/mod-types';

/** Maps EvidenceType to a Tabler icon component */
export const EVIDENCE_TYPE_ICONS: Record<EvidenceType, Icon> = {
  IMAGE: IconPhoto,
  VIDEO: IconVideo,
  AUDIO: IconVolume,
  DOCUMENT: IconFile,
  URL: IconLink,
  DISCORD_URL: IconBrandDiscord,
  MESSAGE_SNAPSHOT: IconCamera,
};

/** Maps amendment actions to Tabler icon components */
export const AMENDMENT_ACTION_ICONS: Record<string, Icon> = {
  NOTE_ADDED: IconNote,
  DESCRIPTION_UPDATED: IconPencil,
  FLAGGED: IconFlag,
  UNFLAGGED: IconFlagOff,
  STATUS_CHANGED: IconRefresh,
};

// Aliases for convenience
const IconGrid = IconLayoutGrid;
const IconCompare = IconArrowsExchange;
const IconRows = IconLayoutRows;

export {
  IconPhoto,
  IconVideo,
  IconVolume,
  IconFile,
  IconLink,
  IconBrandDiscord,
  IconCamera,
  IconNote,
  IconPencil,
  IconFlag,
  IconFlagOff,
  IconRefresh,
  IconDownload,
  IconX,
  IconChevronLeft,
  IconChevronRight,
  IconPlus,
  IconCheck,
  IconAlertTriangle,
  IconQuestionMark,
  IconEye,
  IconHistory,
  IconSettings,
  IconTrash,
  IconSearch,
  IconKeyboard,
  IconLayoutDashboard,
  IconGavel,
  IconFolder,
  IconClipboardList,
  IconShieldCheck,
  IconFilter,
  IconMessageReport,
  IconMenu2,
  IconClipboard,
  IconSend,
  IconTag,
  IconFileExport,
  IconBrush,
  IconPlayerPlay,
  IconPlayerPause,
  IconLayoutGrid,
  IconList,
  IconArrowsExchange,
  IconChartBar,
  IconUser,
  IconCalendar,
  IconUserPlus,
  IconUserMinus,
  IconShare,
  IconColumns,
  IconLayoutRows,
  IconLock,
  IconUsers,
  IconTrophy,
  IconMicrophone,
  IconBan,
  IconMessage,
  IconStarFilled,
  IconLogout,
  // Aliases
  IconGrid,
  IconCompare,
  IconRows,
};
