import type { LogChannelDefinition } from '#lib/types/logging.types.js';

export enum LogType {
  Messages = 'messages',
  Voice = 'voice',
  VoiceState = 'voiceState',
  Tickets = 'tickets',
  Transcripts = 'transcripts',
  Roles = 'roles',
  Channels = 'channels',
  Members = 'members',
  Stage = 'stage',
  Events = 'events',
  Polls = 'polls',
  Emojis = 'emojis',
  Stickers = 'stickers',
  Webhooks = 'webhooks',
  Joins = 'joins',
  Leaves = 'leaves',
  Server = 'server',
}

export const LOG_CHANNEL_DEFINITIONS: Record<LogType, LogChannelDefinition> = {
  [LogType.Messages]: {
    key: 'messages',
    name: 'logs-messages',
    webhookField: 'messagesWebhook',
    enabledField: 'messagesEnabled',
    description: 'Message edits, deletions, and bulk deletes',
    category: 'core',
  },
  [LogType.Voice]: {
    key: 'voice',
    name: 'logs-voice',
    webhookField: 'voiceWebhook',
    enabledField: 'voiceEnabled',
    description: 'Voice channel activity and recordings',
    category: 'core',
  },
  [LogType.VoiceState]: {
    key: 'voiceState',
    name: 'logs-voice-state',
    webhookField: 'voiceStateWebhook',
    enabledField: 'voiceStateEnabled',
    description: 'Voice state changes (mute, deafen, etc.)',
    category: 'core',
  },
  [LogType.Joins]: {
    key: 'joins',
    name: 'logs-member-joins',
    webhookField: 'joinsWebhook',
    enabledField: 'joinsEnabled',
    description: 'Member join events',
    category: 'core',
  },
  [LogType.Leaves]: {
    key: 'leaves',
    name: 'logs-member-leaves',
    webhookField: 'leavesWebhook',
    enabledField: 'leavesEnabled',
    description: 'Member leave and kick events',
    category: 'core',
  },
  [LogType.Members]: {
    key: 'members',
    name: 'logs-members',
    webhookField: 'membersWebhook',
    enabledField: 'membersEnabled',
    description: 'Member updates (nickname, roles, etc.)',
    category: 'core',
  },
  [LogType.Roles]: {
    key: 'roles',
    name: 'logs-roles',
    webhookField: 'rolesWebhook',
    enabledField: 'rolesEnabled',
    description: 'Role creation, deletion, and updates',
    category: 'advanced',
  },
  [LogType.Channels]: {
    key: 'channels',
    name: 'logs-channels',
    webhookField: 'channelsWebhook',
    enabledField: 'channelsEnabled',
    description: 'Channel creation, deletion, and updates',
    category: 'advanced',
  },
  [LogType.Server]: {
    key: 'server',
    name: 'logs-server',
    webhookField: 'serverWebhook',
    enabledField: 'serverEnabled',
    description: 'Server settings and configuration changes',
    category: 'advanced',
  },
  [LogType.Emojis]: {
    key: 'emojis',
    name: 'logs-emojis',
    webhookField: 'emojisWebhook',
    enabledField: 'emojisEnabled',
    description: 'Emoji creation and deletion',
    category: 'advanced',
  },
  [LogType.Stickers]: {
    key: 'stickers',
    name: 'logs-stickers',
    webhookField: 'stickersWebhook',
    enabledField: 'stickersEnabled',
    description: 'Sticker creation and deletion',
    category: 'advanced',
  },
  [LogType.Webhooks]: {
    key: 'webhooks',
    name: 'logs-webhooks',
    webhookField: 'webhooksWebhook',
    enabledField: 'webhooksEnabled',
    description: 'Webhook creation, deletion, and updates',
    category: 'advanced',
  },
  [LogType.Events]: {
    key: 'events',
    name: 'logs-events',
    webhookField: 'eventsWebhook',
    enabledField: 'eventsEnabled',
    description: 'Scheduled events',
    category: 'advanced',
  },
  [LogType.Stage]: {
    key: 'stage',
    name: 'logs-stage',
    webhookField: 'stageWebhook',
    enabledField: 'stageEnabled',
    description: 'Stage channel activity',
    category: 'advanced',
  },
  [LogType.Polls]: {
    key: 'polls',
    name: 'logs-polls',
    webhookField: 'pollsWebhook',
    enabledField: 'pollsEnabled',
    description: 'Poll creation and results',
    category: 'advanced',
  },
  [LogType.Tickets]: {
    key: 'tickets',
    name: 'logs-tickets',
    webhookField: 'ticketsWebhook',
    enabledField: 'ticketsEnabled',
    description: 'Ticket system events',
    category: 'advanced',
  },
  [LogType.Transcripts]: {
    key: 'transcripts',
    name: 'logs-transcripts',
    webhookField: 'transcriptsWebhook',
    enabledField: 'transcriptsEnabled',
    description: 'Ticket transcripts',
    category: 'advanced',
  },
};
