/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 191e198ebe4bcde69f18fff8db4fe0c7)
interface __BaseEnv_CloudflareEnv {
  ASSETS: Fetcher;
  APP_ENV: "development" | "production" | "local";
  BOT_API_INTERNAL_URL:
    | "https://api-dev.catto.one"
    | "https://api.catto.one"
    | "http://localhost:4000";
}
declare namespace Cloudflare {
  interface DevelopmentEnv {
    ASSETS: Fetcher;
    APP_ENV: "development";
    BOT_API_INTERNAL_URL: "https://api-dev.catto.one";
  }
  interface ProductionEnv {
    ASSETS: Fetcher;
    APP_ENV: "production";
    BOT_API_INTERNAL_URL: "https://api.catto.one";
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "APP_ENV" | "BOT_API_INTERNAL_URL">
  > {}
}
